#ifdef _RGBM_SINGLE_STATIC

// Static Light
_RGBM_SINGLE_STATIC(STATIC_LIGHT)

// Breathing
#    ifdef RGBLIGHT_EFFECT_BREATHING
#        ifdef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_SINGLE_DYNAMIC(BREATHING)
#        else
_RGBM_MULTI_DYNAMIC(BREATHING)
_RGBM_TMP_DYNAMIC(breathing_3, BREATHING)
_RGBM_TMP_DYNAMIC(breathing_4, BREATHING)
_RGBM_TMP_DYNAMIC(BREATHING_end, BREATHING)
#        endif
#    endif

// Rainbow Mood
#    ifdef RGBLIGHT_EFFECT_RAINBOW_MOOD
#        ifdef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_SINGLE_DYNAMIC(RAINBOW_MOOD)
#        else
_RGBM_MULTI_DYNAMIC(RAINBOW_MOOD)
_RGBM_TMP_DYNAMIC(rainbow_mood_7, RAINBOW_MOOD)
_RGBM_TMP_DYNAMIC(RAINBOW_MOOD_end, RAINBOW_MOOD)
#        endif
#    endif

// Rainbow Swirl
#    ifdef RGBLIGHT_EFFECT_RAINBOW_SWIRL
#        ifdef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_SINGLE_DYNAMIC(RAINBOW_SWIRL)
#        else
_RGBM_MULTI_DYNAMIC(RAINBOW_SWIRL)
_RGBM_TMP_DYNAMIC(rainbow_swirl_10, RAINBOW_SWIRL)
_RGBM_TMP_DYNAMIC(rainbow_swirl_11, RAINBOW_SWIRL)
_RGBM_TMP_DYNAMIC(rainbow_swirl_12, RAINBOW_SWIRL)
_RGBM_TMP_DYNAMIC(rainbow_swirl_13, RAINBOW_SWIRL)
_RGBM_TMP_DYNAMIC(RAINBOW_SWIRL_end, RAINBOW_SWIRL)
#        endif
#    endif

// Snake
#    ifdef RGBLIGHT_EFFECT_SNAKE
_RGBM_MULTI_DYNAMIC(SNAKE)
// NOTE: Still allow for reverse direction
_RGBM_TMP_DYNAMIC(snake_16, SNAKE)
#        ifndef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_TMP_DYNAMIC(snake_17, SNAKE)
_RGBM_TMP_DYNAMIC(snake_18, SNAKE)
_RGBM_TMP_DYNAMIC(snake_19, SNAKE)
_RGBM_TMP_DYNAMIC(SNAKE_end, SNAKE)
#        endif
#    endif

// Knight
#    ifdef RGBLIGHT_EFFECT_KNIGHT
#        ifdef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_SINGLE_DYNAMIC(KNIGHT)
#        else
_RGBM_MULTI_DYNAMIC(KNIGHT)
_RGBM_TMP_DYNAMIC(knight_22, KNIGHT)
_RGBM_TMP_DYNAMIC(KNIGHT_end, KNIGHT)
#        endif
#    endif

// Christmas
#    ifdef RGBLIGHT_EFFECT_CHRISTMAS
_RGBM_SINGLE_DYNAMIC(CHRISTMAS)
#    endif

// Static Gradient
#    ifdef RGBLIGHT_EFFECT_STATIC_GRADIENT
#        ifdef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_SINGLE_STATIC(STATIC_GRADIENT)
#        else
_RGBM_MULTI_STATIC(STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_26, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_27, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_28, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_29, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_30, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_31, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_32, STATIC_GRADIENT)
_RGBM_TMP_STATIC(static_gradient_33, STATIC_GRADIENT)
_RGBM_TMP_STATIC(STATIC_GRADIENT_end, STATIC_GRADIENT)
#        endif
#    endif

// RGB Test
#    ifdef RGBLIGHT_EFFECT_RGB_TEST
_RGBM_SINGLE_DYNAMIC(RGB_TEST)
#    endif

// Alternating
#    ifdef RGBLIGHT_EFFECT_ALTERNATING
_RGBM_SINGLE_DYNAMIC(ALTERNATING)
#    endif

// Twinkle
#    ifdef RGBLIGHT_EFFECT_TWINKLE
#        ifdef RGBLIGHT_DISABLE_DYNAMIC_STEPS
_RGBM_SINGLE_DYNAMIC(TWINKLE)
#        else
_RGBM_MULTI_DYNAMIC(TWINKLE)
_RGBM_TMP_DYNAMIC(twinkle_38, TWINKLE)
_RGBM_TMP_DYNAMIC(twinkle_39, TWINKLE)
_RGBM_TMP_DYNAMIC(twinkle_40, TWINKLE)
_RGBM_TMP_DYNAMIC(twinkle_41, TWINKLE)
_RGBM_TMP_DYNAMIC(TWINKLE_end, TWINKLE)
#        endif
#    endif

////  Add a new mode here.
// #ifdef RGBLIGHT_EFFECT_<name>
//    _RGBM_<SINGLE|MULTI>_<STATIC|DYNAMIC>( <name> )
// #endif

#endif // _RGBM_SINGLE_STATIC

#undef _RGBM_SINGLE_STATIC
#undef _RGBM_SINGLE_DYNAMIC
#undef _RGBM_MULTI_STATIC
#undef _RGBM_MULTI_DYNAMIC
#undef _RGBM_TMP_STATIC
#undef _RGBM_TMP_DYNAMIC
